# Startup costs in ms
wayang.java.init.ms = 10
wayang.flink.init.ms = 1000
wayang.spark.init.ms = 2500

# Hardware power (CPU MHz)
wayang.java.cpu.mhz = 200
wayang.flink.cpu.mhz = 800
wayang.spark.cpu.mhz = 1000

# Flink Running Mode: use dataset instead of collection to avoid FlinkCollectionSink/CollectionExecutor ClassCastException bugs
wayang.flink.mode.run = dataset